[tool.poetry]
name = "gc-anim-tool"
version = "0.1.0"
description = ""
authors = ["MrPishPIsh <74278948+MrPishPIsh@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
